export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const CHECK_USER_VIEW = 'CHECK_USER_VIEW';

export const CLEAR_USER_VIEW = 'CLEAR_USER_VIEW';
